# Site wide configuration

title: "PowerShell Journey"
description: "Documenting my personal journey in powershell"
logo: site-logo.png
teaser: default-teaser.png
locale: en_US
words_per_minute: 200
title_separator: "-"
url: https://blog.bladefirelight.com
destination: _site

# Site owner

owner:
  name: "David Jones"
  email: BladeFireLight@outlook.com
  twitter: BladeFireLight
  facebook: 
  youtube: 
  instagram: 
  tumblr: 
  github: bladefirelight
  github-repo: 
  paypal-me: BladeFireLight
  cash-me:
  coinbase:
  amazon:
    referral:
    wishlist:   
  wufoo:
    contactform:
  google:
    feedburner: 
    ad-client: 
    ad-slot: 
    analytics: 
    plus: 
    verify: 
  bing:
    verify: 
  alexa:
    verify: 
  yandex:
    verify: 
  bio: "Husband, Father IT Pro. PowerShell enthusiest"
  avatar: avatar1.jpg # 160x160 px image for author byline
disqus-shortname: blogbladefirelightcom


# Jekyll configuration

permalink: /:categories/:title/
lsi: true
markdown: kramdown
kramdown:
  toc_levels: 1..6
highlighter: rouge
keep_files: [.git]
include:
  - .htaccess
  - _pages
  - .nojekyll
exclude:
  - Capfile
  - config
  - log
  - Rakefile
  - tmp
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Gemfile
  - LICENSE
  - README
  - node_modules
  - Gruntfile.js
  - package.json
  - .jekyll-assets-cache
  - .asset-cache
  - .sass-cache
  - .bundle
gems:
  - jekyll-archives
  - jekyll-assets
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-gist
  - jekyll_github_sample

# Collections

collections:
  faqs:
    output: true
    permalink: /:collection/:path/
    title: FAQs
  components:
    output: false
  colors:
    output: false


# Defaults

defaults:

  # All Posts
  - scope:
      path: _posts
      type: posts
    values:
      image:
        feature: sample-image-1.jpg
        teaser: sample-image-1.jpg
        thumb: sample-image-1.jpg



  # Blog Posts
  - scope:
      path: _posts/posts
      type: posts
    values:
      layout: post
      category: posts
      comments: true
      image:
        feature: sample-image-1.jpg
        teaser: sample-image-1.jpg
        thumb: sample-image-1.jpg


  # Projects
  - scope:
      path: _posts/projects
      type: posts
    values:
      layout: post
      category: projects
      comments: true

  # PowerShell Nuggets
  - scope:
      path: _posts/nuggets
      type: posts
    values:
      layout: post
      category: nuggets
      comments: true

  # FAQs
  - scope:
      path: _faqs
      type: faqs
    values:
      layout: post
      comments: true

  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: post

port:    4000


# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development


# Plugin: jekyll-assets

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]

# Plugin: jekyll-archives

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag_index
  permalinks:
    tag: /tag/:name/


# Plugin: jekyll-picture-tag

picture:
  source: "images/_originals"
  output: "images"
  markup: "picture"
  presets:
    default:
      ppi: [1]
      source_720:
        media: "(min-width: 1200px)"
        width: "720"
      source_670:
        media: "(min-width: 768px)"
        width: "670"
      source_540:
        media: "(min-width: 600px)"
        width: "540"
      source_default:
        width: "320"
    hero:
      attr:
        class: "page__hero-image"
        itemprop: "image"
      ppi: [1]
      source_1600:
        media: "(min-width: 1600px)"
        width: "1600"
      source_1024:
        media: "(min-width: 1024px)"
        width: "1024"
      source_768:
        media: "(min-width: 768px)"
        width: "768"
      source_600:
        media: "(min-width: 600px)"
        width: "600"
      source_default:
        width: "320"
